menu:
- {name: 'people', url: '/people'}
- {name: 'publications', url: '/publications'}
- {name: 'teaching', url: '/teaching'}
- {name: 'roots', url: '/roots'}
- {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}

people:
- {
  name: 'Agis Chartsias',
  title: 'Lead Deep Learning Scientist',
  department: 'AI and Computer Vision',
  phone: '',
  institution: 'Ultromics Ltd',
  institution_url: 'https://www.ultromics.com/',
  institution_icon: 'assets/img/people_icons/ULTROMICS.jpg',
  institution_address: 'Oxford, UK',
  email: 'agis.chartsias@ultromics.com',
  image: 'assets/img/agischartsias.jpg',
  url: 'https://www.linkedin.com/in/agis-chartsias/'
}

- {
  name: 'Pablo Lamata',
  title: 'CDT Director in Digital Twins for Healthcare',
  title_url: 'https://www.kcl.ac.uk/research/dt4health-cdt',
  title_icon: 'assets/img/people_icons/CDT.jpg',
  title_additional: 'Group Leader of Cardiac Modelling and Imaging Biomarkers',
  title_additional_url: 'http://cmib.website/',
  title_additional_icon: 'assets/img/people_icons/CMIB.jpg',
  department: 'School of Biomedical Engineering & Imaging Sciences',
  institution: 'King’s College London',
  institution_url: 'https://kclpure.kcl.ac.uk/portal/en/persons/pablo.lamata',
  institution_icon: 'assets/img/people_icons/KCL.png',
  institution_address: 'London, UK',
  email: 'pablo.Lamata@kcl.ac.uk',
  image: 'assets/img/pablolamata.jpg',
  url: 'https://www.linkedin.com/in/pablolamata/'
}

- {
  name: 'Andrew Peter King',
  title: 'Founder of Fairness of AI for Medical Imaging',
  title_url: 'https://faimi-workshop.github.io/',
  title_icon: 'assets/img/people_icons/FAIMI.png',
  title_additional: 'Group Leader of Motion Modelling and Analysis Group',
  title_additional_url: 'https://www.kclmmag.org/',
  title_additional_icon: 'assets/img/people_icons/MMAG.png',
  department: 'School of Biomedical Engineering & Imaging Sciences',
  institution: 'King’s College London',
  institution_url: 'https://www.kcl.ac.uk/people/andrew-king',
  institution_icon: 'assets/img/people_icons/KCL.png',
  institution_address: 'London, UK',
  email: 'andrew.king@kcl.ac.uk',
  image: 'assets/img/andrewking.jpg',
  url: 'https://www.linkedin.com/in/andrew-king-6ab3a949/?originalSubdomain=uk'
}

teaching:
  - title: "Graduate Teaching at King's College London (2019 - 2021)"
    description: "I served as a graduate teaching assistant at King's College London, 
    where I lectured and ran tutorials for up to 40 students on topics ranging from 
    programming and advanced mechanics to computational modeling. It was one of the most 
    challenging (and rewarding) tasks I've ever tackled – more intricate than navigating a labyrinth of curly braces"
    modules:
      - name: "Advanced Mechanics, Level 6 (6CCYB050)"
      - name: "Computational Methods, Level 5 (5CCYB070)"
      - name: "Computer Programming, Level 4 (4CCYB040)"

roots:
  - title: "born"
    image: "/assets/img/roots/gc.jpg"
  - title: "raised"
    image: "/assets/img/roots/southkorea2.jpg"
  - title: "study"
    image: "/assets/img/roots/uk.jpg"
  - title: "abiding in"
    image: "/assets/img/roots/surrey.jpg"
  - title: "next"
    image: "/assets/img/roots/california.jpg"

social:
- {icon: 'github', link: 'https://github.com/woojinchokimm'}
- {icon: 'instagram', link: 'https://instagram.com/woojinchokimm'}
- {icon: 'linkedin', link: 'https://linkedin.com/in/woojinchokim'}
- {icon: 'twitter', link: 'https://twitter.com/woojinchokimm'}

contacts:
- {
  name: 'Woo-Jin Cho Kim',
  title: 'Deep Learning Research Scientist',
  department: 'AI and Computer Vision',
  institution: 'Ultromics Ltd',
  institution_address: "Oxford, UK",
  institution_url: 'https://www.ultromics.com/',
  institution_icon: 'assets/img/people_icons/ULTROMICS.jpg',
  email: 'woojinchokimm@hotmail.com',
  office: '',
  image: 'assets/img/people_icons/contact.jpg'
}